// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screen_screen_init(void)
{
    ui_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logo = lv_img_create(ui_screen);
    lv_img_set_src(ui_Logo, &ui_img_1425725674);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Logo, -195);
    lv_obj_set_y(ui_Logo, -126);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Car = lv_img_create(ui_screen);
    lv_img_set_src(ui_Car, &ui_img_1334565599);
    lv_obj_set_width(ui_Car, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Car, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Car, -75);
    lv_obj_set_y(ui_Car, -21);
    lv_obj_set_align(ui_Car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Car, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Car, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed = lv_label_create(ui_screen);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed, -139);
    lv_obj_set_y(ui_Speed, 119);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "00 Km/h");

    ui_Abs = lv_img_create(ui_screen);
    lv_img_set_src(ui_Abs, &ui_img_1334569699);
    lv_obj_set_width(ui_Abs, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Abs, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Abs, 128);
    lv_obj_set_y(ui_Abs, -22);
    lv_obj_set_align(ui_Abs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Abs, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Abs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Airbag = lv_img_create(ui_screen);
    lv_img_set_src(ui_Airbag, &ui_img_airbag_png);
    lv_obj_set_width(ui_Airbag, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Airbag, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Airbag, 127);
    lv_obj_set_y(ui_Airbag, -89);
    lv_obj_set_align(ui_Airbag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Airbag, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Airbag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Steering = lv_arc_create(ui_screen);
    lv_obj_set_width(ui_Steering, 187);
    lv_obj_set_height(ui_Steering, 186);
    lv_obj_set_x(ui_Steering, -72);
    lv_obj_set_y(ui_Steering, -19);
    lv_obj_set_align(ui_Steering, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Steering, 50);

    ui_Speed1 = lv_label_create(ui_screen);
    lv_obj_set_width(ui_Speed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed1, -5);
    lv_obj_set_y(ui_Speed1, 117);
    lv_obj_set_align(ui_Speed1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed1, "00 Km/h");

    ui_Left = lv_label_create(ui_screen);
    lv_obj_set_width(ui_Left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left, -141);
    lv_obj_set_y(ui_Left, 96);
    lv_obj_set_align(ui_Left, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Left, "L");

    ui_Right = lv_label_create(ui_screen);
    lv_obj_set_width(ui_Right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Right, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Right, -7);
    lv_obj_set_y(ui_Right, 96);
    lv_obj_set_align(ui_Right, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Right, "R");

    ui_SteeringRate = lv_label_create(ui_screen);
    lv_obj_set_width(ui_SteeringRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SteeringRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SteeringRate, -72);
    lv_obj_set_y(ui_SteeringRate, 60);
    lv_obj_set_align(ui_SteeringRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteeringRate, "Steering");

    ui_SteeringIcon = lv_img_create(ui_screen);
    lv_img_set_src(ui_SteeringIcon, &ui_img_1774135500);
    lv_obj_set_width(ui_SteeringIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_SteeringIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_SteeringIcon, 127);
    lv_obj_set_y(ui_SteeringIcon, 50);
    lv_obj_set_align(ui_SteeringIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SteeringIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SteeringIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
