// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_screen
void ui_screen_screen_init(void);
extern lv_obj_t * ui_screen;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Car;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Abs;
extern lv_obj_t * ui_Airbag;
extern lv_obj_t * ui_Steering;
extern lv_obj_t * ui_Speed1;
extern lv_obj_t * ui_Left;
extern lv_obj_t * ui_Right;
extern lv_obj_t * ui_SteeringRate;
extern lv_obj_t * ui_SteeringIcon;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1425725674);    // assets/image-removebg-preview (2).png
LV_IMG_DECLARE(ui_img_1334565599);    // assets/car (3).png
LV_IMG_DECLARE(ui_img_1334569699);    // assets/car (7).png
LV_IMG_DECLARE(ui_img_airbag_png);    // assets/airbag.png
LV_IMG_DECLARE(ui_img_1774135500);    // assets/steering-wheel.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
